### ISSUE TITLE
sum方法为何要转整型？

### ISSUE THREAD

**Issue by see-sea** [thinkkoa/liteQ#4]
return result[0].sum ? (helper.toInt(result[0].sum) || 0) : 0;
源码：adapter.js 336-358行
    sum(field, options = {}) {
        options.method = 'SUM';
        options.limit = [0, 1];
        options.targetField = field;
        return this.query(options).then(result => {
            if (helper.isArray(result)) {
                if (!helper.isEmpty(options.group)) {
                    let res = 0;
                    result.map(it => {
                        const iSum = helper.toInt(it.sum);
                        if (iSum) {
                            res += iSum;
                        }
                    });
                    return res;
                } else {
                    return result[0].sum ? (helper.toInt(result[0].sum) || 0) : 0;
                }
            } else {
                return result.sum || 0;
            }
        });
    }

**Comment by richenlin** [comment]
postgre查询后返回的属性值是string，这里转为int是为了保证不同数据源返回结果一致
