### ISSUE TITLE
怎么判断一个值是否为空？

### ISSUE THREAD

**Issue by kajweb** [thinkkoa/liteQ#5]
如
where("exp", "ISNULL")

**Comment by richenlin** [comment]
`
where({"exp": null})
or
where({"exp": ""})  // not allowd null 
`

**Comment by kajweb** [comment]
相查某个字段为null、""、0只能使用or吗？
{ or:[
    {"_field": null},
    {"_field": ''},
    {"_field": 0},
] }

**Comment by richenlin** [comment]
可以用IN

{"exp":["", null, 0]}

**Comment by kajweb** [comment]
谢谢
